//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmsWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public int Id { get; set; }
        public Nullable<int> GroupSize { get; set; }
        public Nullable<int> DiscountPercentage { get; set; }
        public string Coupon { get; set; }
        public Nullable<int> PromotionDiscount { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> TotalAfterDiscount { get; set; }
    }
}
